@echo off
REM 如果 Windows 7 开始菜单中的文字变成英文，请使用本程序修复

attrib +r "%APPDATA%\Microsoft\Windows\Libraries"
attrib +r "%APPDATA%\Microsoft\Windows\recent"
attrib +r "%APPDATA%\Microsoft\Windows\SendTo"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu\Programs"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\Accessibility"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\System Tools"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Administrative Tools"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Maintenance"
attrib +r "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"

attrib +h +s +r +a "%APPDATA%\Microsoft\Windows\Start Menu\Programs\desktop.ini"
attrib +h +s +r +a "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\desktop.ini"
attrib +h +s +r +a "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\Accessibility\desktop.ini"
attrib +h +s +r +a "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\System Tools\desktop.ini"
attrib +h +s +r +a "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Administrative Tools\desktop.ini"
attrib +h +s +r +a "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Maintenance\desktop.ini"
attrib +h +s +r +a "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\desktop.ini"

attrib +r "%ProgramData%\Microsoft\Windows\Start Menu"
attrib +r "%ProgramData%\Microsoft\Windows\Start Menu\Programs"
attrib +r "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessories"
attrib +r "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessories\Accessibility"
attrib +r "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessories\System Tools"
attrib +r "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Administrative Tools"
attrib +r "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Maintenance"
attrib +r "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Startup"

attrib +h +s +r +a "%ProgramData%\Microsoft\Windows\Start Menu\Programs\desktop.ini"
attrib +h +s +r +a "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessories\desktop.ini"
attrib +h +s +r +a "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessories\Accessibility\desktop.ini"
attrib +h +s +r +a "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessories\System Tools\desktop.ini"
attrib +h +s +r +a "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Administrative Tools\desktop.ini"
attrib +h +s +r +a "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Maintenance\desktop.ini"
attrib +h +s +r +a "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Startup\desktop.ini"